[workspace]
members = [
  "mpv-deno",
  "mpv-qjs",
  "mpv-easy-client",
  # "mpv-boa",
  "mpv-easy-ext",
]
resolver = "2"


[workspace.dependencies]
rquickjs = { version = "0.8.1"  }
once_cell = "1.20.2"
lazy_static = "1.5.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
deno_core = "0.326.0"
mpv-easy-client = { path = "./mpv-easy-client" }
# mpv-client = "0.6.0"
libloading= "0.8.6"