[package]
name = "mpv-easy-client"
version = "0.1.0"
edition = "2021"

[dependencies]
# mpv-client = "0.6.0"
libloading = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
