name: build artifacts
on: workflow_call

jobs:
  build-ext-windows:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: build js
        run: |
          npm install -g pnpm esbuild
          pnpm setup
          pnpm i

          cd ./mpv-js-plugin-init
          pnpm run build

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "nightly"

      - name: build ext
        shell: powershell
        run: |
          $env:RUSTFLAGS="-C target-feature=+crt-static"
          cd ./mpv-easy-ext
          cargo build --target x86_64-pc-windows-msvc --release --out-dir=./output -Z unstable-options
          cd ..
          mv ./mpv-easy-ext/output/mpv-easy-ext.exe ./mpv-easy-ext-windows.exe
          mv ./mpv-easy-ext/output/mpv-easy-play-with.exe ./mpv-easy-play-with-windows.exe


      # - name: build deno
      #   run: |

      #     rustup target add nightly-x86_64-pc-windows-msvc
      #     rustup toolchain install nightly-x86_64-pc-windows-msvc
      #     rustup default nightly-x86_64-pc-windows-msvc
      #     rustup set default-host nightly-x86_64-pc-windows-msvc
      #     rustup override set nightly-x86_64-pc-windows-msvc

      #     rustc --version

      #     cd ./mpv-deno
      #     cargo build --release --out-dir=./output -Z unstable-options
      #     cd ..
      #     mv ./mpv-deno/output/mpv_deno.dll ./mpv-deno-windows.dll
      # - uses: msys2/setup-msys2@v2
      # - shell: msys2 {0}
      #   run: |
      #     pacman -S mingw-w64-x86_64-gcc --noconfirm

      # - name: build qjs
      #   run: |
      #     rustup target add x86_64-pc-windows-gnu
      #     rustup toolchain install nightly-x86_64-pc-windows-gnu
      #     rustup default nightly-x86_64-pc-windows-gnu
      #     rustup set default-host x86_64-pc-windows-gnu
      #     rustup override set nightly-x86_64-pc-windows-gnu
      #     rustc --version

      #     cd ./mpv-qjs
      #     cargo build --release --out-dir=./output -Z unstable-options
      #     cd ..
      #     mv ./mpv-qjs/output/mpv_qjs.dll ./mpv-qjs-windows.dll

      # - name: build boa
      #   run: |
      #     rustup target add x86_64-pc-windows-gnu
      #     rustup toolchain install nightly-x86_64-pc-windows-gnu
      #     rustup default nightly-x86_64-pc-windows-gnu
      #     rustup set default-host x86_64-pc-windows-gnu
      #     rustup override set nightly-x86_64-pc-windows-gnu
      #     rustc --version

      #     cd ./mpv-boa
      #     cargo build --release --out-dir=./output -Z unstable-options
      #     cd ..
      #     mv ./mpv-boa/output/mpv_boa.dll ./mpv-boa-windows.dll

      - name: Upload windows Artifact ext
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-ext-windows
          path: ./mpv-easy-ext-windows.exe
      - name: Upload windows Artifact play-with
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-play-with-windows
          path: ./mpv-easy-play-with-windows.exe

      # - name: Upload windows Artifact deno
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mpv-deno-windows
      #     path: ./mpv-deno-windows.dll

      # - name: Upload windows Artifact qjs
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mpv-qjs-windows
      #     path: ./mpv-qjs-windows.dll
      # - name: Upload windows Artifact boa
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mpv-boa-windows
      #     path: ./mpv-boa-windows.dll

  build-ext-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: build macos-latest
        run: |
          cd ./mpv-easy-ext
          cargo build --release --out-dir=./output -Z unstable-options
          cd ..

          mv ./mpv-easy-ext/output/mpv-easy-ext ./mpv-easy-ext-macos
          mv ./mpv-easy-ext/output/mpv-easy-play-with ./mpv-easy-play-with-macos

      - name: Upload macos Artifact ext
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-ext-macos
          path: ./mpv-easy-ext-macos
      - name: Upload macos Artifact play-with
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-play-with-macos
          path: ./mpv-easy-play-with-macos

  build-ext-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: build ubuntu-latest
        run: |
          cd ./mpv-easy-ext
          cargo build --release --out-dir=./output -Z unstable-options
          cd ..

          mv ./mpv-easy-ext/output/mpv-easy-ext ./mpv-easy-ext-linux
          mv ./mpv-easy-ext/output/mpv-easy-play-with ./mpv-easy-play-with-linux
      - name: Upload ubuntu Artifact ext
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-ext-linux
          path: ./mpv-easy-ext-linux
      - name: Upload ubuntu Artifact play-with
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-play-with-linux
          path: ./mpv-easy-play-with-linux

  build-ext-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: build ubuntu-latest
        run: |

          cd ./mpv-easy-ext

          cargo install cross --git https://github.com/cross-rs/cross
          cross build --release --target aarch64-linux-android --out-dir=./output -Z unstable-options
          cd ..

          mv ./mpv-easy-ext/output/mpv-easy-ext ./mpv-easy-ext-android
          mv ./mpv-easy-ext/output/mpv-easy-play-with ./mpv-easy-play-with-android
      - name: Upload android Artifact ext
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-ext-android
          path: ./mpv-easy-ext-android
      - name: Upload android Artifact play-with
        uses: actions/upload-artifact@v4
        with:
          name: mpv-easy-play-with-android
          path: ./mpv-easy-play-with-android
