name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build-ext:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: build ${{ matrix.runs-on }}
        run: |
          cd ./mpv-rs-ext
          cargo build --release
          cd ..

          npm i pnpm -g
          pnpm i
          cd ./mpv-deno-init
          pnpm run build
          cd ..

          cd ./mpv-deno
          cargo build --release
          cd ..

      - name: windows build
        if: startsWith(matrix.runs-on, 'windows')
        run: |
          mv ./mpv-rs-ext/target/release/rs-ext.exe ./rs-ext-${{ matrix.runs-on }}
          mv ./mpv-deno/target/release/mpv_deno.dll ./mpv-deno-${{ matrix.runs-on }}.dll

      - name: macos build
        if: startsWith(matrix.runs-on, 'macos')
        run: mv ./mpv-rs-ext/target/release/rs-ext ./rs-ext-${{ matrix.runs-on }}
      - name: ubuntu build
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: mv ./mpv-rs-ext/target/release/rs-ext ./rs-ext-${{ matrix.runs-on }}

      - name: Upload ext ${{ matrix.runs-on }} Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rs-ext-${{ matrix.runs-on }}
          path: ./rs-ext-${{ matrix.runs-on }}

      - name: Upload dll ${{ matrix.runs-on }} Artifact
        if: startsWith(matrix.runs-on, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: mpv-deno-${{ matrix.runs-on }}
          path: ./mpv-deno-${{ matrix.runs-on }}.dll

  release:
    needs: [build-ext]
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: bin
          pattern: rs-ext-*
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          path: dll
          pattern: mpv-deno-*
          merge-multiple: true

      - name: "build ts"
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run build

      - name: "create dist"
        run: |
          mkdir ./dist/scripts/mpv-easy-config/bin -p

          cp ./mpv-easy/es5/mpv-easy.js ./dist/scripts/mpv-easy.js
          cp -r ./mpv-easy/fonts ./dist
          cp -r ./mpv-anime4k/shaders ./dist
          cp ./mpv-easy/mpv-conf/mpv.conf ./dist/mpv.conf

          chmod 777 ./bin/*

          cp -r ./dist ./mpy-easy-macos
          cp -r ./dist ./mpy-easy-linux
          cp -r ./dist ./mpy-easy-windows
          cp -r ./dist ./mpy-easy-deno-windows

          cp ./bin/rs-ext-macos-latest ./mpy-easy-macos/scripts/mpv-easy-config/bin/rs-ext-macos
          cp ./bin/rs-ext-ubuntu-latest ./mpy-easy-linux/scripts/mpv-easy-config/bin/rs-ext-linux
          cp ./bin/rs-ext-windows-latest ./mpy-easy-windows/scripts/mpv-easy-config/bin/rs-ext-windows

          cp ./bin/rs-ext-windows-latest ./mpy-easy-deno-windows/scripts/mpv-easy-config/bin/rs-ext-windows
          cp ./dll/mpv-deno-windows-latest.dll ./mpy-easy-deno-windows/scripts/mpv-deno-windows.dll
          rm ./mpy-easy-deno-windows/scripts/mpv-easy.js
          mkdir ./mpy-easy-deno-windows/scripts-deno
          cp ./mpv-easy/bundle/mpv-easy.js ./mpy-easy-deno-windows/scripts-deno/mpv-easy.js

          cd ./mpy-easy-macos
          zip -r -q ./mpy-easy-macos.zip .
          cd ..

          cd ./mpy-easy-linux
          zip -r -q ./mpy-easy-linux.zip .
          cd ..

          cd ./mpy-easy-windows
          zip -r -q ./mpy-easy-windows.zip .
          cd ..

          cd ./mpy-easy-deno-windows
          zip -r -q ./mpy-easy-deno-windows.zip .
          cd ..
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./mpy-easy-deno-windows/mpy-easy-deno-windows.zip,./mpy-easy-windows/mpy-easy-windows.zip,./mpy-easy-linux/mpy-easy-linux.zip,./mpy-easy-macos/mpy-easy-macos.zip"
