name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml

  release:
    needs: [build-artifacts]
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: release
          pattern: release
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
